// Metro for the npm-managed mobile app. The app is self-contained: all source
// lives under the project root (incl. the vendored @trdr/ui at src/trdr-ui.ts,
// regenerated by `pnpm snapshot`) and deps are a flat npm install — so the
// default Expo config bundles cleanly with no monorepo wiring.
//
// Why npm + self-contained: Metro can't resolve pnpm's node_modules layout, and
// cross-package watchFolders are flaky — both avoided by keeping the app local.
const { getDefaultConfig } = require("expo/metro-config");

module.exports = getDefaultConfig(__dirname);
