// Emits a JSON snapshot of real pipeline output for the mobile app to render
// offline (no server needed in Expo Go), and vendors @trdr/ui into the app.
// Run: pnpm snapshot
//
// Uses the SAME buildFeed() the API serves at /api/v1/feed, so the offline
// snapshot and the live response are identical by construction.
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  buildFeed,
  DEMO_FEED_PARAMS,
  DEMO_WISHLIST,
  DEMO_WISHLIST_OPTS,
  scanWishlist,
  selectProviders,
} from "@trdr/ingestion";

async function main() {
  const providers = selectProviders();
  const feed = await buildFeed(providers, DEMO_FEED_PARAMS);
  const wishlist = await scanWishlist(providers, DEMO_WISHLIST, DEMO_WISHLIST_OPTS);

  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const vendorDir = resolve(root, "apps", "mobile", "src");
  mkdirSync(vendorDir, { recursive: true });

  const assetsDir = resolve(root, "apps", "mobile", "assets");
  mkdirSync(assetsDir, { recursive: true });
  // include the flat specs so the app can re-group the tree live as the user adds wishes
  const snapshot = { ...feed, wishlist: { ...wishlist, specs: DEMO_WISHLIST } };
  writeFileSync(resolve(assetsDir, "data.json"), JSON.stringify(snapshot, null, 2), "utf8");
  console.log(
    `✓ wrote apps/mobile/assets/data.json (${feed.alerts.length} alerts, ${wishlist.hits.length} wishlist hits)`,
  );

  // Vendor shared source into the app. Metro reliably watches files under the
  // project root, but cross-package watchFolders are flaky — so the app stays
  // self-contained. Both modules are tiny and re-synced on every snapshot.
  vendor(resolve(root, "packages", "ui", "src", "index.ts"), resolve(vendorDir, "trdr-ui.ts"), "packages/ui/src/index.ts");
  vendor(resolve(root, "packages", "core", "src", "wishlist.ts"), resolve(vendorDir, "trdr-wishlist.ts"), "packages/core/src/wishlist.ts");
  console.log(`✓ vendored @trdr/ui + wishlist → apps/mobile/src/`);

  function vendor(from: string, to: string, label: string) {
    writeFileSync(to, `// GENERATED by \`pnpm snapshot\` from ${label} — do not edit by hand.\n${readFileSync(from, "utf8")}`, "utf8");
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
