// Emits a JSON snapshot of real pipeline output for the mobile app to render
// offline (no server needed in Expo Go), and vendors @trdr/ui into the app.
// Run: pnpm snapshot
//
// Uses the SAME buildFeed() the API serves at /api/v1/feed, so the offline
// snapshot and the live response are identical by construction.
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { buildFeed, DEMO_FEED_PARAMS, selectProviders } from "@trdr/ingestion";

async function main() {
  const feed = await buildFeed(selectProviders(), DEMO_FEED_PARAMS);

  const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

  const assetsDir = resolve(root, "apps", "mobile", "assets");
  mkdirSync(assetsDir, { recursive: true });
  writeFileSync(resolve(assetsDir, "data.json"), JSON.stringify(feed, null, 2), "utf8");
  console.log(`✓ wrote apps/mobile/assets/data.json (${feed.alerts.length} alerts, fair $${feed.passport.fairValue.point.toFixed(0)})`);

  // Vendor @trdr/ui's source into the app. Metro reliably watches files under the
  // project root, but cross-package watchFolders are flaky — so the app stays
  // self-contained. The view-models are tiny and re-synced on every snapshot.
  const uiSrc = readFileSync(resolve(root, "packages", "ui", "src", "index.ts"), "utf8");
  const vendorDir = resolve(root, "apps", "mobile", "src");
  mkdirSync(vendorDir, { recursive: true });
  writeFileSync(
    resolve(vendorDir, "trdr-ui.ts"),
    `// GENERATED by \`pnpm snapshot\` from packages/ui/src/index.ts — do not edit by hand.\n${uiSrc}`,
    "utf8",
  );
  console.log(`✓ vendored @trdr/ui → apps/mobile/src/trdr-ui.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
